version: "3.8"

services:
  nginx-jwt:
    container_name: nginx-jwt
#    image: nginx-jwt:latest
    ports:
      - "80:80"
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
#    volumes:
#      - ./frontend/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./frontend/nginx/localhost+3-key.pub:/etc/nginx/localhost+3-key.pub
    depends_on:
        - petstore
    restart: unless-stopped
  jiraproxy:
    image: jiraproxy:latest
    container_name: jiraproxy
    build:
      context: ./backend/web-proxy
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    restart: unless-stopped
  vehicles-api:
    image: vehicles-api:latest
    container_name: vehicles-api
    build:
      context: ./backend/vehicles-api
      dockerfile: Dockerfile
    ports:
      - 8880:8880
    restart: unless-stopped
  petstore:
    image: petstore:latest
    container_name: petstore
    build:
      context: ./backend/petstore
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    environment:
      - DOCKER_HOST_IP=host.docker.internal
    restart: unless-stopped
  cloudapp:
    image: cloudapp:latest
    container_name: cloudapp
    build:
      context: ./backend/cloudapp
      dockerfile: Dockerfile
    ports:
      - 8099:8099
    environment:
      - DOCKER_HOST_IP=host.docker.internal
      - DOCKER_HOST_KAFKA_PORT=9092
    restart: unless-stopped
  mlops-segmentation:
    build:
      context: ./backend/ml-pipeline
      dockerfile: Dockerfile
    container_name: mlops-segmentation
    ports:
      - 8600:8600
    environment:
      - DOCKER_HOST_IP=host.docker.internal
  next-frontend:
    build:
      context: ./frontend/cloudapp
      dockerfile: Dockerfile
    container_name: next-frontend
    ports:
      - 5001:5001
    environment:
      - DOCKER_HOST_IP=host.docker.internal
  next-openmaps:
    build:
      context: ./frontend/remote/openmaps
      dockerfile: Dockerfile
    container_name: next-openmaps
    ports:
      - 5002:5002
    environment:
      - DOCKER_HOST_IP=host.docker.internal